### ISSUE TITLE
Make the Chatrooms List of Users be Dynamic

### ISSUE THREAD

**Issue by shiBinH** [CSC59939/Chitty-Chat#62]
- possible addition of a service to retrieve room information

**Comment by bidachen** [comment]
I think chatroom list should be another collection that store some chatrooms information we gonna use and id (for getting chatroom history). so we dont have to query each chatroom to get its info.

**Comment by shiBinH** [comment]
Sounds reasonable. I think a good name would be ChatroomMetadata?

**Comment by bidachen** [comment]
I just checked firebase datatype, there is a map datatype to store data like a object, we can use it maybe. and for friendlist we might need to do the same thing?

**Comment by shiBinH** [comment]
Is the use case for these collections to retrieve the entire collection of metadata and then search through them for chatrooms/friends that of the user?

**Comment by bidachen** [comment]
I am not sure if I understood your question. What I was thinking is to store some metadata we need, like chatroom name or friend name that we need to show them when user want to know the list of chatrooms he joined or list of friends he has. And id is used when user enter a chatroom, we query the chat history for the chatroom.

**Comment by shiBinH** [comment]
Just to clarify, you want to change array of chatrooms/friendlist currently on the user documents to a collection of maps of metadata?

**Comment by shiBinH** [comment]
The issue I see in user's keeping independent metadata is that updates to chatrooms/user information will also require looking through and updating every user's self kept metadata. But since our application does not support modifying existing information this is not a real concern, yet.

**Comment by bidachen** [comment]
https://stackoverflow.com/questions/46568850/what-is-firestore-reference-data-type-good-for/46570119#46570119
it seems like querying a document reference is not that hard?
