### ISSUE TITLE
write emotions of each message to the database

### ISSUE THREAD

**Issue by FarhanHyder** [CSC59939/Chitty-Chat#70]
- analyze the emotion of a chat message 
- write the emotion to the database
- each `chat` table should have a `emotion` field (we already have this)

**Comment by shiBinH** [comment]
This seems to overlap with #69?

**Comment by FarhanHyder** [comment]
> This seems to overlap with #69?

Predicting emotions involves using IBM Watson thingy to predict emotion of a sentence. 
Which is actually the `analyze the emotion of a chat message` part.
However, after predicting it - we will need it to write to the database. That's what this part is mostly about.

**Comment by FarhanHyder** [comment]
completed
