### ISSUE TITLE
Does Nikolai expect a domain name

### ISSUE THREAD

**Issue by kawyua** [CSC59939/Chitty-Chat#73]
making a domain name costs money, but it seems straightfoward:
https://console.aws.amazon.com/route53/home?#DomainRegistration:

We may have to ask nikolai to fund this?
currently nikolai said that this link was bad.
https://chitty-chat-balancer-1464536969.us-east-1.elb.amazonaws.com/

**Comment by shiBinH** [comment]
I can look I to this. I'm already using student credits for our aws resources

**Comment by kawyua** [comment]
@shiBinH This turned out really simple with bitly.
http://bit.ly/chitty-chat

I made an account that redirects to your chittychat link. Its free, too. Think this is good enough
